import os
from qtpy import QtCore, QtWidgets
from .qtd import Ui_MainWindow
from .cakehistwidget import CakeHistogramWidget
from ..utils import SpinBoxFixStyle
from ..version import __version__
from ..citation import __citation__
from ..utils import InformationBox
# exec(open(os.path.join(os.path.curdir, 'version.py')).read())
# exec(open(os.path.join(os.path.curdir, 'citation.py')).read())


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    """
    Main window
    """

    def __init__(self, parent=None):
        # initialization of the superclass
        super(MainWindow, self).__init__(parent)
        self.setupUi(self)  # setup the GUI --> function generated by pyuic5
        try:
            env = os.environ['CONDA_DEFAULT_ENV']
        except:
            env = 'unknown'
        self.setWindowTitle("PeakPo ver. " + str(__version__) + " on " + env)
        #
        self.build_ui()
        self.connect_channel()
        # the two lines needs to be considred for move from this widget file
        self.actionCiting_PeakPo.triggered.connect(self.about)
        self.actionShortcut_keys.triggered.connect(self.shortcutkeys)

    def build_ui(self):
        # self.pushButton_MakeBasePtn.setEnabled(False)
        """ This was unstable feature but from 06/18/2022 it is enabled.
        self.pushButton_SetJCPDSStepTo0001.setDisabled(True)
        self.pushButton_SetJCPDSStepTo001.setDisabled(True)
        self.pushButton_SetJCPDSStepTo01.setDisabled(True)
        self.pushButton_UpdateJCPDSSteps.setDisabled(True)
        self.doubleSpinBox_JCPDSStep.setDisabled(True)
        """
        self.doubleSpinBox_JCPDSStep.setKeyboardTracking(False)
        self.doubleSpinBox_JCPDSStep.setStyle(SpinBoxFixStyle())
        self.doubleSpinBox_Pressure.setKeyboardTracking(False)
        self.doubleSpinBox_Pressure.setStyle(SpinBoxFixStyle())
        self.doubleSpinBox_Temperature.setKeyboardTracking(False)
        self.doubleSpinBox_Temperature.setStyle(SpinBoxFixStyle())
        self.spinBox_BGParam0.setKeyboardTracking(False)
        self.spinBox_BGParam1.setKeyboardTracking(False)
        self.spinBox_BGParam2.setKeyboardTracking(False)
        self.spinBox_BGParam0.setStyle(SpinBoxFixStyle())
        self.spinBox_BGParam1.setStyle(SpinBoxFixStyle())
        self.spinBox_BGParam2.setStyle(SpinBoxFixStyle())
        self.doubleSpinBox_Background_ROI_max.setKeyboardTracking(False)
        self.doubleSpinBox_Background_ROI_min.setKeyboardTracking(False)
        self.doubleSpinBox_Background_ROI_max.setStyle(SpinBoxFixStyle())
        self.doubleSpinBox_Background_ROI_min.setStyle(SpinBoxFixStyle())
        self.doubleSpinBox_SetWavelength.setKeyboardTracking(False)
        self.doubleSpinBox_SetWavelength.setStyle(SpinBoxFixStyle())
        linethicknesses = ['0', '0.1', '0.2', '0.5', '0.75',
                           '1', '1.5', '2', '3', '4', '5']
        self.comboBox_BasePtnLineThickness.addItems(linethicknesses)
        self.comboBox_PtnJCPDSBarThickness.addItems(linethicknesses)
        self.comboBox_CakeJCPDSBarThickness.addItems(linethicknesses)
        self.comboBox_BkgnLineThickness.addItems(linethicknesses)
        self.comboBox_WaterfallLineThickness.addItems(linethicknesses)
        self.comboBox_VertCursorThickness.addItems(linethicknesses)
        self.comboBox_BasePtnLineThickness.setCurrentText('1')
        self.comboBox_PtnJCPDSBarThickness.setCurrentText('1')
        self.comboBox_CakeJCPDSBarThickness.setCurrentText('0.5')
        self.comboBox_BkgnLineThickness.setCurrentText('0.5')
        self.comboBox_WaterfallLineThickness.setCurrentText('0.5')
        self.comboBox_VertCursorThickness.setCurrentText('1')
        fontsizes = ['4', '6', '8', '10', '12', '14', '16', '18', '20', '24',
                     '28', '36', '42']
        self.comboBox_HKLFontSize.addItems(fontsizes)
        self.comboBox_HKLFontSize.setCurrentText('8')
        self.comboBox_PnTFontSize.addItems(fontsizes)
        self.comboBox_PnTFontSize.setCurrentText('16')
        self.label_LegendFontSize = QtWidgets.QLabel(self.groupBox_13)
        self.label_LegendFontSize.setText("Legend")
        self.comboBox_LegendFontSize = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox_LegendFontSize.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_LegendFontSize.addItems(fontsizes)
        self.comboBox_LegendFontSize.setCurrentText('12')
        self.label_WaterfallFontSize = QtWidgets.QLabel(self.groupBox_13)
        self.label_WaterfallFontSize.setText("Waterfall label")
        self.comboBox_WaterfallFontSize = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox_WaterfallFontSize.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_WaterfallFontSize.addItems(fontsizes)
        self.comboBox_WaterfallFontSize.setCurrentText('12')
        self.comboBox_PnTFontSize.setMinimumWidth(96)
        self.comboBox_HKLFontSize.setMinimumWidth(96)
        self.comboBox_LegendFontSize.setMinimumWidth(96)
        self.comboBox_WaterfallFontSize.setMinimumWidth(96)
        self.comboBox_PnTFontSize.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox_HKLFontSize.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox_LegendFontSize.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox_WaterfallFontSize.setLayoutDirection(QtCore.Qt.RightToLeft)
        # Rebuild the original QtDesigner row layout to avoid inherited spacer
        # artifacts and match the "Line thickness" left/right arrangement.
        while self.horizontalLayout_4.count():
            item = self.horizontalLayout_4.takeAt(0)
            w = item.widget()
            if w is not None:
                w.hide()
        self._font_size_grid = QtWidgets.QGridLayout()
        self._font_size_grid.setContentsMargins(0, 0, 0, 0)
        self._font_size_grid.setHorizontalSpacing(18)
        self._font_size_grid.setVerticalSpacing(8)
        self._font_size_grid.setColumnStretch(2, 1)
        self.label_15.show()
        self.comboBox_PnTFontSize.show()
        self.label_3.show()
        self.comboBox_HKLFontSize.show()
        self.label_LegendFontSize.show()
        self.comboBox_LegendFontSize.show()
        self.label_WaterfallFontSize.show()
        self.comboBox_WaterfallFontSize.show()
        self._font_size_grid.addWidget(self.label_15, 0, 0)
        self._font_size_grid.addWidget(self.comboBox_PnTFontSize, 0, 1)
        self._font_size_grid.addWidget(self.label_3, 0, 3)
        self._font_size_grid.addWidget(self.comboBox_HKLFontSize, 0, 4)
        self._font_size_grid.addWidget(self.label_LegendFontSize, 1, 0)
        self._font_size_grid.addWidget(self.comboBox_LegendFontSize, 1, 1)
        self._font_size_grid.addWidget(self.label_WaterfallFontSize, 1, 3)
        self._font_size_grid.addWidget(self.comboBox_WaterfallFontSize, 1, 4)
        self.horizontalLayout_4.addLayout(self._font_size_grid)
        self.comboBox_Symmetry.addItems(['cubic', 'tetragonal',
                                         'hexagonal', 'orthorhombic'])
        self.comboBox_Symmetry.setCurrentText('cubic')
        self._setup_plot_subtabs()
        # Legacy toolbar save icon is replaced by the session Save button.
        if hasattr(self, "pushButton_S_SaveSession"):
            self.pushButton_S_SaveSession.setVisible(False)
        self.tableWidget_DiffImgAzi.\
            setHorizontalHeaderLabels(['Notes', '2th', 'Azi', '2th', 'Azi'])
        # Gray scale panel now includes histogram controls; relax hard height cap
        # from the UI file so top controls (e.g., Reset Scale) are not clipped.
        self.groupBox_29.setMinimumHeight(340)
        self.groupBox_29.setMaximumHeight(600)
        # The top gray-scale row in qtd.py is constrained too tightly (25 px
        # frame + vertical layout margins), which clips the Reset Scale button.
        self.frame_8.setMinimumHeight(34)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.pushButton_ResetCakeScale.setMinimumHeight(28)
        self.spinBox_MaxCakeScale.setMinimumHeight(28)
        self.verticalLayout_11.setSpacing(4)
        self.label_19.setFixedHeight(18)
        self.label_19.setContentsMargins(0, 0, 0, 0)
        # Histogram controls replace manual Min/Max slider interaction.
        self.label_8.setVisible(False)
        self.horizontalSlider_VMin.setVisible(False)
        self.label_9.setVisible(False)
        self.horizontalSlider_VMax.setVisible(False)
        self.cake_hist_widget = CakeHistogramWidget(self.groupBox_29)
        self.cake_hist_widget.setMinimumHeight(140)
        self.verticalLayout_11.insertWidget(1, self.cake_hist_widget)
        self._fix_tab_clipping()
        # navigation toolbar modification
        """
        self.ntb_WholePtn = QtWidgets.QPushButton()
        self.ntb_WholePtn.setText("Z")
        self.ntb_WholePtn.setToolTip("Zoom Out")
        self.mpl.ntb.addWidget(self.ntb_WholePtn)
        self.ntb_SaveSession = QtWidgets.QPushButton()
        self.ntb_SaveSession.setText("S")
        self.ntb_SaveSession.setToolTip("Save dpp and ppss")
        self.mpl.ntb.addWidget(self.ntb_SaveSession)
        self.ntb_toPkFt = QtWidgets.QPushButton()
        self.ntb_toPkFt.setText("toPkFt")
        self.mpl.ntb.addWidget(self.ntb_toPkFt)
        self.ntb_fromPkFt = QtWidgets.QPushButton()
        self.ntb_fromPkFt.setText("fromPkFt")
        self.mpl.ntb.addWidget(self.ntb_fromPkFt)
        self.ntb_ResetY = QtWidgets.QCheckBox()
        self.ntb_ResetY.setCheckable(True)
        self.ntb_ResetY.setChecked(False)
        self.ntb_ResetY.setText("AutoYScale")
        self.mpl.ntb.addWidget(self.ntb_ResetY)
        self.ntb_Bgsub = QtWidgets.QCheckBox()
        self.ntb_Bgsub.setCheckable(True)
        self.ntb_Bgsub.setChecked(True)
        self.ntb_Bgsub.setText("BgSub")
        self.mpl.ntb.addWidget(self.ntb_Bgsub)
        self.ntb_NightView = QtWidgets.QCheckBox()
        self.ntb_NightView.setCheckable(True)
        self.ntb_NightView.setChecked(True)
        self.ntb_NightView.setText("Night")
        self.mpl.ntb.addWidget(self.ntb_NightView)
        """

    def _fix_tab_clipping(self):
        # Keep native tab visuals while nudging tab size metrics to prevent
        # clipped ascenders/descenders on some Qt style+font combinations.
        class _NoClipTabStyle(QtWidgets.QProxyStyle):
            def sizeFromContents(self, contents_type, option, size, widget=None):
                sized = super().sizeFromContents(
                    contents_type, option, size, widget)
                if contents_type == QtWidgets.QStyle.CT_TabBarTab:
                    sized.setHeight(sized.height() + 4)
                return sized

        self._tabbar_styles = []
        tab_widgets = [
            self.tabWidget, self.tabWidget_3, self.tabWidget1,
            self.tabWidget_5, self.tabWidget_2, self.tabWidget_4,
            self.tabWidget_PeakFit
        ]
        if hasattr(self, "tabWidget_PlotSub"):
            tab_widgets.append(self.tabWidget_PlotSub)
        for tab_widget in tab_widgets:
            bar = tab_widget.tabBar()
            bar.setStyleSheet("")
            bar.setExpanding(False)
            tab_style = _NoClipTabStyle(bar.style())
            self._tabbar_styles.append(tab_style)
            bar.setStyle(tab_style)

    def _setup_plot_subtabs(self):
        # Build nested tabs inside Plot: Control / Config.
        # Keep original widget IDs so existing controller wiring still works.
        while self.verticalLayout_44.count():
            item = self.verticalLayout_44.takeAt(0)
            w = item.widget()
            if w is not None:
                w.hide()
                w.setParent(None)

        self.tabWidget_PlotSub = QtWidgets.QTabWidget(self.tab_Plot)
        self.tabWidget_PlotSub.setObjectName("tabWidget_PlotSub")

        self.tab_PlotControl = QtWidgets.QWidget()
        self.tab_PlotControl.setObjectName("tab_PlotControl")
        self._plot_ctrl_layout = QtWidgets.QVBoxLayout(self.tab_PlotControl)
        self._plot_ctrl_layout.setContentsMargins(0, 0, 0, 0)
        self.scrollArea_PlotControl = QtWidgets.QScrollArea(self.tab_PlotControl)
        self.scrollArea_PlotControl.setWidgetResizable(True)
        self.scrollArea_PlotControl.setObjectName("scrollArea_PlotControl")
        self.plotControlContents = QtWidgets.QWidget()
        self.plotControlContents.setObjectName("plotControlContents")
        self.verticalLayout_PlotControl = QtWidgets.QVBoxLayout(self.plotControlContents)
        self.verticalLayout_PlotControl.setObjectName("verticalLayout_PlotControl")
        self.scrollArea_PlotControl.setWidget(self.plotControlContents)
        self._plot_ctrl_layout.addWidget(self.scrollArea_PlotControl)

        self.tab_PlotConfig = QtWidgets.QWidget()
        self.tab_PlotConfig.setObjectName("tab_PlotConfig")
        self._plot_cfg_layout = QtWidgets.QVBoxLayout(self.tab_PlotConfig)
        self._plot_cfg_layout.setContentsMargins(0, 0, 0, 0)
        self.scrollArea_PlotConfig = QtWidgets.QScrollArea(self.tab_PlotConfig)
        self.scrollArea_PlotConfig.setWidgetResizable(True)
        self.scrollArea_PlotConfig.setObjectName("scrollArea_PlotConfig")
        self.plotConfigContents = QtWidgets.QWidget()
        self.plotConfigContents.setObjectName("plotConfigContents")
        self.verticalLayout_PlotConfig = QtWidgets.QVBoxLayout(self.plotConfigContents)
        self.verticalLayout_PlotConfig.setObjectName("verticalLayout_PlotConfig")
        self.scrollArea_PlotConfig.setWidget(self.plotConfigContents)
        self._plot_cfg_layout.addWidget(self.scrollArea_PlotConfig)

        self.tabWidget_PlotSub.addTab(self.tab_PlotControl, "Control")
        self.tabWidget_PlotSub.addTab(self.tab_PlotConfig, "Config")
        self.verticalLayout_44.addWidget(self.tabWidget_PlotSub)

        # Control tab: plot control + JCPDS bars + cake display controls
        self.groupBox_34.setParent(self.plotControlContents)
        self.groupBox_20.setParent(self.plotControlContents)
        self.groupBox_29.setParent(self.plotControlContents)
        self.groupBox_5.setParent(self.plotControlContents)
        self.groupBox_23.setParent(self.plotControlContents)
        self.verticalLayout_PlotControl.addWidget(self.groupBox_34)
        self.verticalLayout_PlotControl.addWidget(self.groupBox_20)
        self.verticalLayout_PlotControl.addWidget(self.groupBox_29)
        self.verticalLayout_PlotControl.addWidget(self.groupBox_5)
        self.verticalLayout_PlotControl.addWidget(self.groupBox_23)
        self.verticalLayout_PlotControl.addStretch(1)

        # Config tab: remaining plot config groups
        self.groupBox_16.setParent(self.plotConfigContents)
        self.groupBox_24.setParent(self.plotConfigContents)
        self.groupBox_13.setParent(self.plotConfigContents)
        self.groupBox_27.setParent(self.plotConfigContents)
        self.verticalLayout_PlotConfig.addWidget(self.groupBox_16)
        self.verticalLayout_PlotConfig.addWidget(self.groupBox_24)
        self.verticalLayout_PlotConfig.addWidget(self.groupBox_13)
        self.verticalLayout_PlotConfig.addWidget(self.groupBox_27)
        self.verticalLayout_PlotConfig.addStretch(1)

    def closeEvent(self, event):
        try:
            if hasattr(self, 'mpl') and hasattr(self.mpl, 'shutdown'):
                self.mpl.shutdown()
        except Exception:
            pass
        super().closeEvent(event)

    def connect_channel(self):
        self.pushButton_RoomT.clicked.connect(
            lambda: self.set_temperature(300))
        self.pushButton_S_RoomT.clicked.connect(
            lambda: self.set_temperature(300))
        self.pushButton_1bar.clicked.connect(
            lambda: self.set_pressure(0.0))
        self.pushButton_SetPStepTo1.clicked.connect(
            lambda: self.set_q_pstep(1.))
        self.pushButton_SetPStepTo10.clicked.connect(
            lambda: self.set_q_pstep(10.))
        self.pushButton_SetTStepTo100.clicked.connect(
            lambda: self.set_q_tstep(100))
        self.pushButton_SetTStepTo1000.clicked.connect(
            lambda: self.set_q_tstep(1000))
        self.doubleSpinBox_PStep.valueChanged.connect(self.set_pstep)
        self.spinBox_TStep.valueChanged.connect(self.set_tstep)
        """
        self.pushButton_SetUCFitStepTo0_01.clicked.connect(
            lambda: self.set_ustep(0.01))
        self.pushButton_SetUCFitStepTo0_001.clicked.connect(
            lambda: self.set_ustep(0.001))
        self.pushButton_SetUCFitStepTo0_0001.clicked.connect(
            lambda: self.set_ustep(0.0001))
        """
        self.pushButton_SetJCPDSStepTo0001.clicked.connect(
            lambda: self.set_jstep(0.001))
        self.pushButton_SetJCPDSStepTo001.clicked.connect(
            lambda: self.set_jstep(0.01))
        self.pushButton_SetJCPDSStepTo01.clicked.connect(
            lambda: self.set_jstep(0.1))
        self.pushButton_AboutPeakpo.clicked.connect(self.about)
        self.pushButton_Help.clicked.connect(self.shortcutkeys)

    """
    def set_ustep(self, value):
        self.doubleSpinBox_UCFitStep.setValue(value)
    """

    def set_jstep(self, value):
        self.doubleSpinBox_JCPDSStep.setValue(value)

    def set_pstep(self):
        self.doubleSpinBox_Pressure.setSingleStep(
            self.doubleSpinBox_PStep.value())

    def set_tstep(self):
        self.doubleSpinBox_Temperature.setSingleStep(
            self.spinBox_TStep.value())

    def set_temperature(self, temperature):
        self.doubleSpinBox_Temperature.setValue(temperature)

    def set_pressure(self, pressure):
        self.doubleSpinBox_Pressure.setValue(pressure)

    def set_q_pstep(self, value=1.):
        self.doubleSpinBox_PStep.setValue(value)

    def set_q_tstep(self, value=1000.):
        self.spinBox_TStep.setValue(value)

    def about(self):
        information = 'PeakPo ver.' + __version__ + '<br>' + \
            'A Visual Diffraction Analysis Tool<br>' + \
            'by S.-H. Dan Shim, SHDShim@gmail.com<br>' + \
            'Arizona State University<br><br>' + \
            'Source: https://github.com/SHDShim/peakpo-v7 <br><br>' + \
            'Manual: https://github.com/SHDShim/PeakPo/wiki <br><br>' + \
            'how to cite: ' + str(__citation__) + '<br><br>' + \
            'WARNING. Use at your own risk. ' + \
            'This is a free software and no support is provided.<br>'
        infobox = InformationBox(title="About PeakPo")
        infobox.setText(information)
        infobox.exec()

        """
        self.textEdit_about.setText(
            'PeakPo ver.' + __version__ + '<br>' +
            'A Visual Diffraction Analysis Tool<br>' +
            'by S.-H. Dan Shim, SHDShim@gmail.com<br>' +
            'Arizona State University<br><br>' +
            'Source: https://github.com/SHDShim/peakpo-v7 <br><br>' +
            'Manual: https://github.com/SHDShim/PeakPo/wiki <br><br>'
            'how to cite: ' + str(__citation__) + '<br><br>'
            'WARNING. Use at your own risk. ' +
            'This is a free software and no support is provided.<br>')
        """

    def shortcutkeys(self):
        information = '** Shortcut Keys ** <br><br>' + \
            'To activate shortcut keys: <br>' + \
            ' - Mouse click the plotting area. <br>' + \
            ' - Make sure no toolbar buttons are in blue. <br><br>' + \
            'Save session: s<br>' + \
            'Rescale vertical: v<br>' + \
            'Whole spectrum: w<br>' + \
            'Home or Reset: H or R<br>' + \
            'Back: left arrow<br>' + \
            'Forward: right arrow<br>' + \
            'Pan: p<br>' + \
            'Zoom: o<br>' + \
            'Peak position read: i<br>' + \
            'Constrain pan/zoom to x axis: hold x when panning/zooming<br>' + \
            'Constrain pan/zoom to y axis: hold y when panning/zooming<br>' + \
            'Preserve aspect ratio: hold CTRL when panning/zooming<br>' + \
            'Toggle x scale (log/lin): L or k when mouse is over an axes<br>' + \
            'Toggle y scale (log/lin): l when mouse is over an axes<br>'
        infobox = InformationBox(title="Help")
        infobox.setText(information)
        infobox.exec()

        """
        self.textEdit_shortcuts.setText(
            '** Shortcut Keys ** <br><br>' +
            'To activate shortcut keys: <br>' +
            ' - Mouse click the plotting area. <br>' +
            ' - Make sure no toolbar buttons are in blue. <br><br>' +
            'Save session: s<br>' +
            'Rescale vertical: v<br>' +
            'Whole spectrum: w<br>' +
            'Home or Reset: H or R<br>' +
            'Back: left arrow<br>' +
            'Forward: right arrow<br>' +
            'Pan: p<br>' +
            'Zoom: o<br>' +
            'Peak position read: i<br>' +
            'Constrain pan/zoom to x axis: hold x when panning/zooming<br>' +
            'Constrain pan/zoom to y axis: hold y when panning/zooming<br>' +
            'Preserve aspect ratio: hold CTRL when panning/zooming<br>' +
            'Toggle x scale (log/lin): L or k when mouse is over an axes<br>' +
            'Toggle y scale (log/lin): l when mouse is over an axes<br>')
        """
