"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

A few things I had to do:
- /Users/DanShim/anaconda/lib/python2.7/site-packages/macholib/MachOGraph.py", line 49
I changed line 49 in macOGraph from loader=loader.filename)
to loader_path=loader.filename)

    
"""

from setuptools import setup
import PyQt4
import sys
sys.setrecursionlimit(1500)

APP = ['peakpo.py']
DATA_FILES = []
includes = ['PyQt4.QtCore','PyQt4.QtGui']
#frameworks = ['/Users/DanShim/anaconda/lib/libQtSvg.dylib', \
#              '/Users/DanShim/anaconda/lib/python2.7/lib-dynload/_hashlib.so']

OPTIONS = {'argv_emulation': True, 'includes': includes,
           'iconfile': 'icon/PeakPo.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
