# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtd-pkpo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1449, 723)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("font: 12pt \"Helvetica\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mpl = MplWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mpl.setFont(font)
        self.mpl.setObjectName("mpl")
        self.verticalLayout.addWidget(self.mpl)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 220))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 200))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Files = QtWidgets.QWidget()
        self.tab_Files.setObjectName("tab_Files")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_Files)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_SessionFileName = QtWidgets.QLabel(self.tab_Files)
        self.label_SessionFileName.setObjectName("label_SessionFileName")
        self.verticalLayout_14.addWidget(self.label_SessionFileName)
        self.label_DiffractionPatternFileName = QtWidgets.QLabel(self.tab_Files)
        self.label_DiffractionPatternFileName.setObjectName("label_DiffractionPatternFileName")
        self.verticalLayout_14.addWidget(self.label_DiffractionPatternFileName)
        self.label_DiffractionImageFilename = QtWidgets.QLabel(self.tab_Files)
        self.label_DiffractionImageFilename.setObjectName("label_DiffractionImageFilename")
        self.verticalLayout_14.addWidget(self.label_DiffractionImageFilename)
        self.label_PONI = QtWidgets.QLabel(self.tab_Files)
        self.label_PONI.setObjectName("label_PONI")
        self.verticalLayout_14.addWidget(self.label_PONI)
        self.label_Jlist = QtWidgets.QLabel(self.tab_Files)
        self.label_Jlist.setObjectName("label_Jlist")
        self.verticalLayout_14.addWidget(self.label_Jlist)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_Files, "")
        self.tab_Main = QtWidgets.QWidget()
        self.tab_Main.setObjectName("tab_Main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_Main)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_LoadSession = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_LoadSession.sizePolicy().hasHeightForWidth())
        self.pushButton_LoadSession.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_LoadSession.setFont(font)
        self.pushButton_LoadSession.setObjectName("pushButton_LoadSession")
        self.verticalLayout_4.addWidget(self.pushButton_LoadSession)
        self.pushButton_SaveSession = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SaveSession.sizePolicy().hasHeightForWidth())
        self.pushButton_SaveSession.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_SaveSession.setFont(font)
        self.pushButton_SaveSession.setObjectName("pushButton_SaveSession")
        self.verticalLayout_4.addWidget(self.pushButton_SaveSession)
        self.pushButton_ZipSession = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ZipSession.sizePolicy().hasHeightForWidth())
        self.pushButton_ZipSession.setSizePolicy(sizePolicy)
        self.pushButton_ZipSession.setObjectName("pushButton_ZipSession")
        self.verticalLayout_4.addWidget(self.pushButton_ZipSession)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setBaseSize(QtCore.QSize(250, 0))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_NewBasePtn = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_NewBasePtn.sizePolicy().hasHeightForWidth())
        self.pushButton_NewBasePtn.setSizePolicy(sizePolicy)
        self.pushButton_NewBasePtn.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_NewBasePtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_NewBasePtn.setBaseSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_NewBasePtn.setFont(font)
        self.pushButton_NewBasePtn.setToolTip("")
        self.pushButton_NewBasePtn.setWhatsThis("")
        self.pushButton_NewBasePtn.setObjectName("pushButton_NewBasePtn")
        self.verticalLayout_3.addWidget(self.pushButton_NewBasePtn)
        self.doubleSpinBox_SetWavelength = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_SetWavelength.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_SetWavelength.setSizePolicy(sizePolicy)
        self.doubleSpinBox_SetWavelength.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_SetWavelength.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBox_SetWavelength.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_SetWavelength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_SetWavelength.setDecimals(4)
        self.doubleSpinBox_SetWavelength.setSingleStep(0.0001)
        self.doubleSpinBox_SetWavelength.setProperty("value", 0.3344)
        self.doubleSpinBox_SetWavelength.setObjectName("doubleSpinBox_SetWavelength")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_SetWavelength)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_24.sizePolicy().hasHeightForWidth())
        self.groupBox_24.setSizePolicy(sizePolicy)
        self.groupBox_24.setFlat(False)
        self.groupBox_24.setObjectName("groupBox_24")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_24)
        self.horizontalLayout_3.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_FirstBasePtn = QtWidgets.QPushButton(self.groupBox_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_FirstBasePtn.sizePolicy().hasHeightForWidth())
        self.pushButton_FirstBasePtn.setSizePolicy(sizePolicy)
        self.pushButton_FirstBasePtn.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_FirstBasePtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_FirstBasePtn.setObjectName("pushButton_FirstBasePtn")
        self.horizontalLayout_3.addWidget(self.pushButton_FirstBasePtn)
        self.pushButton_PrevBasePtn = QtWidgets.QPushButton(self.groupBox_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_PrevBasePtn.sizePolicy().hasHeightForWidth())
        self.pushButton_PrevBasePtn.setSizePolicy(sizePolicy)
        self.pushButton_PrevBasePtn.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_PrevBasePtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_PrevBasePtn.setObjectName("pushButton_PrevBasePtn")
        self.horizontalLayout_3.addWidget(self.pushButton_PrevBasePtn)
        self.pushButton_NextBasePtn = QtWidgets.QPushButton(self.groupBox_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_NextBasePtn.sizePolicy().hasHeightForWidth())
        self.pushButton_NextBasePtn.setSizePolicy(sizePolicy)
        self.pushButton_NextBasePtn.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_NextBasePtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_NextBasePtn.setObjectName("pushButton_NextBasePtn")
        self.horizontalLayout_3.addWidget(self.pushButton_NextBasePtn)
        self.pushButton_LastBasePtn = QtWidgets.QPushButton(self.groupBox_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_LastBasePtn.sizePolicy().hasHeightForWidth())
        self.pushButton_LastBasePtn.setSizePolicy(sizePolicy)
        self.pushButton_LastBasePtn.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_LastBasePtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_LastBasePtn.setObjectName("pushButton_LastBasePtn")
        self.horizontalLayout_3.addWidget(self.pushButton_LastBasePtn)
        self.horizontalLayout.addWidget(self.groupBox_24)
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_21.sizePolicy().hasHeightForWidth())
        self.groupBox_21.setSizePolicy(sizePolicy)
        self.groupBox_21.setFlat(False)
        self.groupBox_21.setObjectName("groupBox_21")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_14.setTitle("")
        self.groupBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_5.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_FileStep1 = QtWidgets.QRadioButton(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_FileStep1.sizePolicy().hasHeightForWidth())
        self.radioButton_FileStep1.setSizePolicy(sizePolicy)
        self.radioButton_FileStep1.setChecked(True)
        self.radioButton_FileStep1.setObjectName("radioButton_FileStep1")
        self.horizontalLayout_5.addWidget(self.radioButton_FileStep1)
        self.radioButton_FileStep10 = QtWidgets.QRadioButton(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_FileStep10.sizePolicy().hasHeightForWidth())
        self.radioButton_FileStep10.setSizePolicy(sizePolicy)
        self.radioButton_FileStep10.setObjectName("radioButton_FileStep10")
        self.horizontalLayout_5.addWidget(self.radioButton_FileStep10)
        self.verticalLayout_11.addWidget(self.groupBox_14)
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_23.sizePolicy().hasHeightForWidth())
        self.groupBox_23.setSizePolicy(sizePolicy)
        self.groupBox_23.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_23.setTitle("")
        self.groupBox_23.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_23.setObjectName("groupBox_23")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_23)
        self.horizontalLayout_6.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_SortbyNme = QtWidgets.QRadioButton(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_SortbyNme.sizePolicy().hasHeightForWidth())
        self.radioButton_SortbyNme.setSizePolicy(sizePolicy)
        self.radioButton_SortbyNme.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.radioButton_SortbyNme.setChecked(True)
        self.radioButton_SortbyNme.setObjectName("radioButton_SortbyNme")
        self.horizontalLayout_6.addWidget(self.radioButton_SortbyNme)
        self.radioButton_SortbyTime = QtWidgets.QRadioButton(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_SortbyTime.sizePolicy().hasHeightForWidth())
        self.radioButton_SortbyTime.setSizePolicy(sizePolicy)
        self.radioButton_SortbyTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.radioButton_SortbyTime.setObjectName("radioButton_SortbyTime")
        self.horizontalLayout_6.addWidget(self.radioButton_SortbyTime)
        self.verticalLayout_11.addWidget(self.groupBox_23)
        self.horizontalLayout.addWidget(self.groupBox_21)
        self.groupBox = QtWidgets.QGroupBox(self.tab_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.doubleSpinBox_Pressure = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_Pressure.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_Pressure.setSizePolicy(sizePolicy)
        self.doubleSpinBox_Pressure.setMinimumSize(QtCore.QSize(0, 60))
        self.doubleSpinBox_Pressure.setSizeIncrement(QtCore.QSize(0, 0))
        self.doubleSpinBox_Pressure.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_Pressure.setFont(font)
        self.doubleSpinBox_Pressure.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBox_Pressure.setStyleSheet("font: 75 24pt \"Helvetica\";")
        self.doubleSpinBox_Pressure.setFrame(False)
        self.doubleSpinBox_Pressure.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_Pressure.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_Pressure.setDecimals(1)
        self.doubleSpinBox_Pressure.setMaximum(1000.0)
        self.doubleSpinBox_Pressure.setProperty("value", 10.0)
        self.doubleSpinBox_Pressure.setObjectName("doubleSpinBox_Pressure")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_Pressure)
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_9.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.radioButton_P10 = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_P10.setObjectName("radioButton_P10")
        self.gridLayout_9.addWidget(self.radioButton_P10, 1, 0, 1, 1)
        self.radioButton_P100 = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_P100.setObjectName("radioButton_P100")
        self.gridLayout_9.addWidget(self.radioButton_P100, 1, 1, 1, 1)
        self.radioButton_P01 = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_P01.setObjectName("radioButton_P01")
        self.gridLayout_9.addWidget(self.radioButton_P01, 0, 0, 1, 1)
        self.radioButton_P1 = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_P1.setChecked(True)
        self.radioButton_P1.setObjectName("radioButton_P1")
        self.gridLayout_9.addWidget(self.radioButton_P1, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_16)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.doubleSpinBox_Temperature = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_Temperature.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_Temperature.setSizePolicy(sizePolicy)
        self.doubleSpinBox_Temperature.setMinimumSize(QtCore.QSize(0, 60))
        self.doubleSpinBox_Temperature.setBaseSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_Temperature.setFont(font)
        self.doubleSpinBox_Temperature.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBox_Temperature.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_Temperature.setAutoFillBackground(False)
        self.doubleSpinBox_Temperature.setStyleSheet("font: 75 24pt \"Helvetica\";")
        self.doubleSpinBox_Temperature.setFrame(False)
        self.doubleSpinBox_Temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_Temperature.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_Temperature.setDecimals(0)
        self.doubleSpinBox_Temperature.setMaximum(10000.0)
        self.doubleSpinBox_Temperature.setSingleStep(100.0)
        self.doubleSpinBox_Temperature.setProperty("value", 300.0)
        self.doubleSpinBox_Temperature.setObjectName("doubleSpinBox_Temperature")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_Temperature)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_10.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.radioButton_T100 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_T100.setChecked(True)
        self.radioButton_T100.setObjectName("radioButton_T100")
        self.gridLayout_10.addWidget(self.radioButton_T100, 1, 0, 1, 1)
        self.radioButton_T10 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_T10.setObjectName("radioButton_T10")
        self.gridLayout_10.addWidget(self.radioButton_T10, 0, 1, 1, 1)
        self.radioButton_T1 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_T1.setObjectName("radioButton_T1")
        self.gridLayout_10.addWidget(self.radioButton_T1, 0, 0, 1, 1)
        self.radioButton_T1000 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_T1000.setObjectName("radioButton_T1000")
        self.gridLayout_10.addWidget(self.radioButton_T1000, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_17)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_6.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_2000K = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2000K.sizePolicy().hasHeightForWidth())
        self.pushButton_2000K.setSizePolicy(sizePolicy)
        self.pushButton_2000K.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2000K.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2000K.setFont(font)
        self.pushButton_2000K.setObjectName("pushButton_2000K")
        self.gridLayout_6.addWidget(self.pushButton_2000K, 6, 0, 1, 1)
        self.pushButton_3000K = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3000K.sizePolicy().hasHeightForWidth())
        self.pushButton_3000K.setSizePolicy(sizePolicy)
        self.pushButton_3000K.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3000K.setFont(font)
        self.pushButton_3000K.setObjectName("pushButton_3000K")
        self.gridLayout_6.addWidget(self.pushButton_3000K, 2, 1, 1, 1)
        self.pushButton_1000K = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1000K.sizePolicy().hasHeightForWidth())
        self.pushButton_1000K.setSizePolicy(sizePolicy)
        self.pushButton_1000K.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_1000K.setFont(font)
        self.pushButton_1000K.setObjectName("pushButton_1000K")
        self.gridLayout_6.addWidget(self.pushButton_1000K, 2, 0, 1, 1)
        self.pushButton_1500K = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1500K.sizePolicy().hasHeightForWidth())
        self.pushButton_1500K.setSizePolicy(sizePolicy)
        self.pushButton_1500K.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_1500K.setFont(font)
        self.pushButton_1500K.setObjectName("pushButton_1500K")
        self.gridLayout_6.addWidget(self.pushButton_1500K, 4, 0, 1, 1)
        self.pushButton_RoomT = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RoomT.sizePolicy().hasHeightForWidth())
        self.pushButton_RoomT.setSizePolicy(sizePolicy)
        self.pushButton_RoomT.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_RoomT.setFont(font)
        self.pushButton_RoomT.setObjectName("pushButton_RoomT")
        self.gridLayout_6.addWidget(self.pushButton_RoomT, 0, 0, 1, 1)
        self.pushButton_2500K = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2500K.sizePolicy().hasHeightForWidth())
        self.pushButton_2500K.setSizePolicy(sizePolicy)
        self.pushButton_2500K.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2500K.setFont(font)
        self.pushButton_2500K.setObjectName("pushButton_2500K")
        self.gridLayout_6.addWidget(self.pushButton_2500K, 0, 1, 1, 1)
        self.pushButton_3500K = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_3500K.setObjectName("pushButton_3500K")
        self.gridLayout_6.addWidget(self.pushButton_3500K, 4, 1, 1, 1)
        self.pushButton_4000K = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_4000K.setObjectName("pushButton_4000K")
        self.gridLayout_6.addWidget(self.pushButton_4000K, 6, 1, 1, 1)
        self.pushButton_4500K = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_4500K.setObjectName("pushButton_4500K")
        self.gridLayout_6.addWidget(self.pushButton_4500K, 0, 2, 1, 1)
        self.pushButton_5000K = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_5000K.setObjectName("pushButton_5000K")
        self.gridLayout_6.addWidget(self.pushButton_5000K, 2, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_11)
        self.tabWidget.addTab(self.tab_Main, "")
        self.tab_Waterfall = QtWidgets.QWidget()
        self.tab_Waterfall.setObjectName("tab_Waterfall")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_Waterfall)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_Waterfall)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_17.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.checkBox_SetToBasePtnLambda = QtWidgets.QCheckBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_SetToBasePtnLambda.sizePolicy().hasHeightForWidth())
        self.checkBox_SetToBasePtnLambda.setSizePolicy(sizePolicy)
        self.checkBox_SetToBasePtnLambda.setChecked(True)
        self.checkBox_SetToBasePtnLambda.setObjectName("checkBox_SetToBasePtnLambda")
        self.verticalLayout_17.addWidget(self.checkBox_SetToBasePtnLambda)
        self.checkBox_BasePtnBackground = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_BasePtnBackground.setChecked(True)
        self.checkBox_BasePtnBackground.setObjectName("checkBox_BasePtnBackground")
        self.verticalLayout_17.addWidget(self.checkBox_BasePtnBackground)
        self.checkBox_IntNorm = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_IntNorm.setObjectName("checkBox_IntNorm")
        self.verticalLayout_17.addWidget(self.checkBox_IntNorm)
        self.pushButton_ApplyWaterfallChange = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_ApplyWaterfallChange.setObjectName("pushButton_ApplyWaterfallChange")
        self.verticalLayout_17.addWidget(self.pushButton_ApplyWaterfallChange)
        self.horizontalLayout_7.addWidget(self.groupBox_6)
        self.groupBox_28 = QtWidgets.QGroupBox(self.tab_Waterfall)
        self.groupBox_28.setObjectName("groupBox_28")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_28)
        self.verticalLayout_20.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.doubleSpinBox_WaterfallGaps = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_WaterfallGaps.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_WaterfallGaps.setSizePolicy(sizePolicy)
        self.doubleSpinBox_WaterfallGaps.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_WaterfallGaps.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBox_WaterfallGaps.setFrame(True)
        self.doubleSpinBox_WaterfallGaps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_WaterfallGaps.setMaximum(1.0)
        self.doubleSpinBox_WaterfallGaps.setSingleStep(0.01)
        self.doubleSpinBox_WaterfallGaps.setProperty("value", 0.1)
        self.doubleSpinBox_WaterfallGaps.setObjectName("doubleSpinBox_WaterfallGaps")
        self.verticalLayout_20.addWidget(self.doubleSpinBox_WaterfallGaps)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem1)
        self.horizontalLayout_7.addWidget(self.groupBox_28)
        self.groupBox_26 = QtWidgets.QGroupBox(self.tab_Waterfall)
        self.groupBox_26.setObjectName("groupBox_26")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_26)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_AddPatterns = QtWidgets.QPushButton(self.groupBox_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddPatterns.sizePolicy().hasHeightForWidth())
        self.pushButton_AddPatterns.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_AddPatterns.setFont(font)
        self.pushButton_AddPatterns.setObjectName("pushButton_AddPatterns")
        self.verticalLayout_15.addWidget(self.pushButton_AddPatterns)
        self.pushButton_RemovePatterns = QtWidgets.QPushButton(self.groupBox_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RemovePatterns.sizePolicy().hasHeightForWidth())
        self.pushButton_RemovePatterns.setSizePolicy(sizePolicy)
        self.pushButton_RemovePatterns.setObjectName("pushButton_RemovePatterns")
        self.verticalLayout_15.addWidget(self.pushButton_RemovePatterns)
        self.pushButton_CleanPatterns = QtWidgets.QPushButton(self.groupBox_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_CleanPatterns.sizePolicy().hasHeightForWidth())
        self.pushButton_CleanPatterns.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_CleanPatterns.setFont(font)
        self.pushButton_CleanPatterns.setObjectName("pushButton_CleanPatterns")
        self.verticalLayout_15.addWidget(self.pushButton_CleanPatterns)
        self.horizontalLayout_7.addWidget(self.groupBox_26)
        self.groupBox_27 = QtWidgets.QGroupBox(self.tab_Waterfall)
        self.groupBox_27.setObjectName("groupBox_27")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_27)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_UpPattern = QtWidgets.QPushButton(self.groupBox_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_UpPattern.sizePolicy().hasHeightForWidth())
        self.pushButton_UpPattern.setSizePolicy(sizePolicy)
        self.pushButton_UpPattern.setObjectName("pushButton_UpPattern")
        self.verticalLayout_16.addWidget(self.pushButton_UpPattern)
        self.pushButton_DownPattern = QtWidgets.QPushButton(self.groupBox_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DownPattern.sizePolicy().hasHeightForWidth())
        self.pushButton_DownPattern.setSizePolicy(sizePolicy)
        self.pushButton_DownPattern.setObjectName("pushButton_DownPattern")
        self.verticalLayout_16.addWidget(self.pushButton_DownPattern)
        self.pushButton_MakeBasePtn = QtWidgets.QPushButton(self.groupBox_27)
        self.pushButton_MakeBasePtn.setObjectName("pushButton_MakeBasePtn")
        self.verticalLayout_16.addWidget(self.pushButton_MakeBasePtn)
        self.horizontalLayout_7.addWidget(self.groupBox_27)
        self.tableWidget_wfPatterns = QtWidgets.QTableWidget(self.tab_Waterfall)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_wfPatterns.sizePolicy().hasHeightForWidth())
        self.tableWidget_wfPatterns.setSizePolicy(sizePolicy)
        self.tableWidget_wfPatterns.setMinimumSize(QtCore.QSize(300, 0))
        self.tableWidget_wfPatterns.setMaximumSize(QtCore.QSize(1200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_wfPatterns.setFont(font)
        self.tableWidget_wfPatterns.setObjectName("tableWidget_wfPatterns")
        self.tableWidget_wfPatterns.setColumnCount(0)
        self.tableWidget_wfPatterns.setRowCount(0)
        self.horizontalLayout_7.addWidget(self.tableWidget_wfPatterns)
        self.tabWidget.addTab(self.tab_Waterfall, "")
        self.tabCake = QtWidgets.QWidget()
        self.tabCake.setObjectName("tabCake")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabCake)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tabCake)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_AddRemoveCake = QtWidgets.QPushButton(self.groupBox_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddRemoveCake.sizePolicy().hasHeightForWidth())
        self.pushButton_AddRemoveCake.setSizePolicy(sizePolicy)
        self.pushButton_AddRemoveCake.setCheckable(True)
        self.pushButton_AddRemoveCake.setObjectName("pushButton_AddRemoveCake")
        self.verticalLayout_10.addWidget(self.pushButton_AddRemoveCake)
        self.pushButton_GetPONI = QtWidgets.QPushButton(self.groupBox_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_GetPONI.sizePolicy().hasHeightForWidth())
        self.pushButton_GetPONI.setSizePolicy(sizePolicy)
        self.pushButton_GetPONI.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_GetPONI.setObjectName("pushButton_GetPONI")
        self.verticalLayout_10.addWidget(self.pushButton_GetPONI)
        self.horizontalLayout_4.addWidget(self.groupBox_18)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.groupBox_20 = QtWidgets.QGroupBox(self.tabCake)
        self.groupBox_20.setObjectName("groupBox_20")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_8.setContentsMargins(-1, 6, 12, 6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_29 = QtWidgets.QGroupBox(self.groupBox_20)
        self.groupBox_29.setTitle("")
        self.groupBox_29.setObjectName("groupBox_29")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_29)
        self.gridLayout_13.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_13.setVerticalSpacing(1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_29)
        self.label_9.setObjectName("label_9")
        self.gridLayout_13.addWidget(self.label_9, 1, 0, 1, 1)
        self.spinBox_VMax = QtWidgets.QSpinBox(self.groupBox_29)
        self.spinBox_VMax.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_VMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_VMax.setMaximum(1000000)
        self.spinBox_VMax.setSingleStep(1)
        self.spinBox_VMax.setProperty("value", 1000000)
        self.spinBox_VMax.setObjectName("spinBox_VMax")
        self.gridLayout_13.addWidget(self.spinBox_VMax, 1, 1, 1, 1)
        self.spinBox_VMin = QtWidgets.QSpinBox(self.groupBox_29)
        self.spinBox_VMin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_VMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_VMin.setMaximum(1000000)
        self.spinBox_VMin.setObjectName("spinBox_VMin")
        self.gridLayout_13.addWidget(self.spinBox_VMin, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_29)
        self.label_8.setObjectName("label_8")
        self.gridLayout_13.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_29)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 2, 0, 1, 1)
        self.spinBox_CakeAxisSize = QtWidgets.QSpinBox(self.groupBox_29)
        self.spinBox_CakeAxisSize.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_CakeAxisSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_CakeAxisSize.setMinimum(1)
        self.spinBox_CakeAxisSize.setObjectName("spinBox_CakeAxisSize")
        self.gridLayout_13.addWidget(self.spinBox_CakeAxisSize, 2, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_29)
        self.pushButton_ApplyCakeView = QtWidgets.QPushButton(self.groupBox_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ApplyCakeView.sizePolicy().hasHeightForWidth())
        self.pushButton_ApplyCakeView.setSizePolicy(sizePolicy)
        self.pushButton_ApplyCakeView.setObjectName("pushButton_ApplyCakeView")
        self.horizontalLayout_8.addWidget(self.pushButton_ApplyCakeView)
        self.horizontalLayout_4.addWidget(self.groupBox_20)
        self.groupBox_22 = QtWidgets.QGroupBox(self.tabCake)
        self.groupBox_22.setObjectName("groupBox_22")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_22)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_30 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_30.setTitle("")
        self.groupBox_30.setObjectName("groupBox_30")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_30)
        self.gridLayout_11.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_10 = QtWidgets.QLabel(self.groupBox_30)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_30)
        self.label_11.setObjectName("label_11")
        self.gridLayout_11.addWidget(self.label_11, 2, 0, 1, 1)
        self.spinBox_MaskMin = QtWidgets.QSpinBox(self.groupBox_30)
        self.spinBox_MaskMin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_MaskMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_MaskMin.setMaximum(10000000)
        self.spinBox_MaskMin.setObjectName("spinBox_MaskMin")
        self.gridLayout_11.addWidget(self.spinBox_MaskMin, 0, 1, 1, 1)
        self.spinBox_MaskMax = QtWidgets.QSpinBox(self.groupBox_30)
        self.spinBox_MaskMax.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_MaskMax.setMaximum(10000000)
        self.spinBox_MaskMax.setProperty("value", 10000000)
        self.spinBox_MaskMax.setObjectName("spinBox_MaskMax")
        self.gridLayout_11.addWidget(self.spinBox_MaskMax, 2, 1, 1, 1)
        self.horizontalLayout_9.addWidget(self.groupBox_30)
        self.pushButton_ApplyMask = QtWidgets.QPushButton(self.groupBox_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ApplyMask.sizePolicy().hasHeightForWidth())
        self.pushButton_ApplyMask.setSizePolicy(sizePolicy)
        self.pushButton_ApplyMask.setCheckable(True)
        self.pushButton_ApplyMask.setObjectName("pushButton_ApplyMask")
        self.horizontalLayout_9.addWidget(self.pushButton_ApplyMask)
        self.horizontalLayout_4.addWidget(self.groupBox_22)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.groupBox_19 = QtWidgets.QGroupBox(self.tabCake)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_BackToOriginal = QtWidgets.QPushButton(self.groupBox_19)
        self.pushButton_BackToOriginal.setObjectName("pushButton_BackToOriginal")
        self.verticalLayout_13.addWidget(self.pushButton_BackToOriginal)
        self.pushButton_Reintegrate1D = QtWidgets.QPushButton(self.groupBox_19)
        self.pushButton_Reintegrate1D.setObjectName("pushButton_Reintegrate1D")
        self.verticalLayout_13.addWidget(self.pushButton_Reintegrate1D)
        self.pushButton_OuputCHI = QtWidgets.QPushButton(self.groupBox_19)
        self.pushButton_OuputCHI.setObjectName("pushButton_OuputCHI")
        self.verticalLayout_13.addWidget(self.pushButton_OuputCHI)
        self.horizontalLayout_4.addWidget(self.groupBox_19)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.tabWidget.addTab(self.tabCake, "")
        self.tabJCPDSList = QtWidgets.QWidget()
        self.tabJCPDSList.setObjectName("tabJCPDSList")
        self.gridLayout = QtWidgets.QGridLayout(self.tabJCPDSList)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tabJCPDSList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_NewJlist = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_NewJlist.sizePolicy().hasHeightForWidth())
        self.pushButton_NewJlist.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_NewJlist.setFont(font)
        self.pushButton_NewJlist.setObjectName("pushButton_NewJlist")
        self.verticalLayout_7.addWidget(self.pushButton_NewJlist)
        self.pushButton_LoadJlist = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_LoadJlist.sizePolicy().hasHeightForWidth())
        self.pushButton_LoadJlist.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_LoadJlist.setFont(font)
        self.pushButton_LoadJlist.setObjectName("pushButton_LoadJlist")
        self.verticalLayout_7.addWidget(self.pushButton_LoadJlist)
        self.pushButton_SaveJlist = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SaveJlist.sizePolicy().hasHeightForWidth())
        self.pushButton_SaveJlist.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_SaveJlist.setFont(font)
        self.pushButton_SaveJlist.setObjectName("pushButton_SaveJlist")
        self.verticalLayout_7.addWidget(self.pushButton_SaveJlist)
        self.pushButton_ExportXLS = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_ExportXLS.setObjectName("pushButton_ExportXLS")
        self.verticalLayout_7.addWidget(self.pushButton_ExportXLS)
        self.gridLayout.addWidget(self.groupBox_9, 0, 0, 2, 1)
        self.tableWidget_JCPDS = QtWidgets.QTableWidget(self.tabJCPDSList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_JCPDS.sizePolicy().hasHeightForWidth())
        self.tableWidget_JCPDS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_JCPDS.setFont(font)
        self.tableWidget_JCPDS.setWordWrap(False)
        self.tableWidget_JCPDS.setColumnCount(0)
        self.tableWidget_JCPDS.setObjectName("tableWidget_JCPDS")
        self.tableWidget_JCPDS.setRowCount(0)
        self.tableWidget_JCPDS.horizontalHeader().setVisible(False)
        self.tableWidget_JCPDS.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_JCPDS.verticalHeader().setVisible(False)
        self.tableWidget_JCPDS.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.tableWidget_JCPDS, 1, 3, 1, 2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabJCPDSList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_CheckAllJCPDS = QtWidgets.QPushButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_CheckAllJCPDS.setFont(font)
        self.pushButton_CheckAllJCPDS.setObjectName("pushButton_CheckAllJCPDS")
        self.verticalLayout_6.addWidget(self.pushButton_CheckAllJCPDS)
        self.pushButton_UncheckAllJCPDS = QtWidgets.QPushButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_UncheckAllJCPDS.setFont(font)
        self.pushButton_UncheckAllJCPDS.setObjectName("pushButton_UncheckAllJCPDS")
        self.verticalLayout_6.addWidget(self.pushButton_UncheckAllJCPDS)
        self.checkBox_Intensity = QtWidgets.QCheckBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Intensity.sizePolicy().hasHeightForWidth())
        self.checkBox_Intensity.setSizePolicy(sizePolicy)
        self.checkBox_Intensity.setChecked(True)
        self.checkBox_Intensity.setObjectName("checkBox_Intensity")
        self.verticalLayout_6.addWidget(self.checkBox_Intensity)
        self.spinBox_LowestJCPDSInt = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_LowestJCPDSInt.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_LowestJCPDSInt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_LowestJCPDSInt.setProperty("value", 1)
        self.spinBox_LowestJCPDSInt.setObjectName("spinBox_LowestJCPDSInt")
        self.verticalLayout_6.addWidget(self.spinBox_LowestJCPDSInt)
        self.gridLayout.addWidget(self.groupBox_7, 0, 1, 2, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabJCPDSList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_AddToJlist = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddToJlist.sizePolicy().hasHeightForWidth())
        self.pushButton_AddToJlist.setSizePolicy(sizePolicy)
        self.pushButton_AddToJlist.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_AddToJlist.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_AddToJlist.setFont(font)
        self.pushButton_AddToJlist.setObjectName("pushButton_AddToJlist")
        self.gridLayout_3.addWidget(self.pushButton_AddToJlist, 0, 0, 1, 1)
        self.pushButton_RemoveJCPDS = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RemoveJCPDS.sizePolicy().hasHeightForWidth())
        self.pushButton_RemoveJCPDS.setSizePolicy(sizePolicy)
        self.pushButton_RemoveJCPDS.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_RemoveJCPDS.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_RemoveJCPDS.setFont(font)
        self.pushButton_RemoveJCPDS.setObjectName("pushButton_RemoveJCPDS")
        self.gridLayout_3.addWidget(self.pushButton_RemoveJCPDS, 0, 1, 1, 1)
        self.pushButton_MoveUp = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_MoveUp.sizePolicy().hasHeightForWidth())
        self.pushButton_MoveUp.setSizePolicy(sizePolicy)
        self.pushButton_MoveUp.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_MoveUp.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_MoveUp.setFont(font)
        self.pushButton_MoveUp.setObjectName("pushButton_MoveUp")
        self.gridLayout_3.addWidget(self.pushButton_MoveUp, 1, 0, 1, 1)
        self.pushButton_MoveDown = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_MoveDown.sizePolicy().hasHeightForWidth())
        self.pushButton_MoveDown.setSizePolicy(sizePolicy)
        self.pushButton_MoveDown.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_MoveDown.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_MoveDown.setFont(font)
        self.pushButton_MoveDown.setObjectName("pushButton_MoveDown")
        self.gridLayout_3.addWidget(self.pushButton_MoveDown, 1, 1, 1, 1)
        self.pushButton_ExportToUCFit = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ExportToUCFit.sizePolicy().hasHeightForWidth())
        self.pushButton_ExportToUCFit.setSizePolicy(sizePolicy)
        self.pushButton_ExportToUCFit.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_ExportToUCFit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_ExportToUCFit.setObjectName("pushButton_ExportToUCFit")
        self.gridLayout_3.addWidget(self.pushButton_ExportToUCFit, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_8, 0, 2, 2, 1)
        self.tabWidget.addTab(self.tabJCPDSList, "")
        self.tabUnitCellFit = QtWidgets.QWidget()
        self.tabUnitCellFit.setObjectName("tabUnitCellFit")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabUnitCellFit)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tabUnitCellFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_15.sizePolicy().hasHeightForWidth())
        self.groupBox_15.setSizePolicy(sizePolicy)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_12.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_RemoveUClist = QtWidgets.QPushButton(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RemoveUClist.sizePolicy().hasHeightForWidth())
        self.pushButton_RemoveUClist.setSizePolicy(sizePolicy)
        self.pushButton_RemoveUClist.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton_RemoveUClist.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_RemoveUClist.setFont(font)
        self.pushButton_RemoveUClist.setObjectName("pushButton_RemoveUClist")
        self.verticalLayout_12.addWidget(self.pushButton_RemoveUClist)
        self.pushButton_ExportXLS_2 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_ExportXLS_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_ExportXLS_2.setObjectName("pushButton_ExportXLS_2")
        self.verticalLayout_12.addWidget(self.pushButton_ExportXLS_2)
        self.horizontalLayout_2.addWidget(self.groupBox_15)
        self.tableWidget_UnitCell = QtWidgets.QTableWidget(self.tabUnitCellFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_UnitCell.sizePolicy().hasHeightForWidth())
        self.tableWidget_UnitCell.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_UnitCell.setFont(font)
        self.tableWidget_UnitCell.setWordWrap(False)
        self.tableWidget_UnitCell.setColumnCount(0)
        self.tableWidget_UnitCell.setObjectName("tableWidget_UnitCell")
        self.tableWidget_UnitCell.setRowCount(0)
        self.tableWidget_UnitCell.horizontalHeader().setVisible(False)
        self.tableWidget_UnitCell.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_UnitCell.verticalHeader().setVisible(False)
        self.tableWidget_UnitCell.verticalHeader().setCascadingSectionResizes(True)
        self.horizontalLayout_2.addWidget(self.tableWidget_UnitCell)
        self.tabWidget.addTab(self.tabUnitCellFit, "")
        self.tabOutput = QtWidgets.QWidget()
        self.tabOutput.setObjectName("tabOutput")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabOutput)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEdit_ViewJCPDS = QtWidgets.QPlainTextEdit(self.tabOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_ViewJCPDS.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_ViewJCPDS.setSizePolicy(sizePolicy)
        self.plainTextEdit_ViewJCPDS.setObjectName("plainTextEdit_ViewJCPDS")
        self.gridLayout_2.addWidget(self.plainTextEdit_ViewJCPDS, 0, 2, 3, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tabOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.groupBox_12.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_8.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_ViewJCPDS = QtWidgets.QPushButton(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ViewJCPDS.sizePolicy().hasHeightForWidth())
        self.pushButton_ViewJCPDS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_ViewJCPDS.setFont(font)
        self.pushButton_ViewJCPDS.setObjectName("pushButton_ViewJCPDS")
        self.verticalLayout_8.addWidget(self.pushButton_ViewJCPDS)
        self.pushButton_SaveCHI = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_SaveCHI.setObjectName("pushButton_SaveCHI")
        self.verticalLayout_8.addWidget(self.pushButton_SaveCHI)
        self.pushButton_SaveXY = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_SaveXY.setObjectName("pushButton_SaveXY")
        self.verticalLayout_8.addWidget(self.pushButton_SaveXY)
        self.pushButton_SaveJCPDS = QtWidgets.QPushButton(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SaveJCPDS.sizePolicy().hasHeightForWidth())
        self.pushButton_SaveJCPDS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_SaveJCPDS.setFont(font)
        self.pushButton_SaveJCPDS.setObjectName("pushButton_SaveJCPDS")
        self.verticalLayout_8.addWidget(self.pushButton_SaveJCPDS)
        self.gridLayout_2.addWidget(self.groupBox_12, 0, 0, 3, 1)
        self.tabWidget.addTab(self.tabOutput, "")
        self.tabDiffPattern = QtWidgets.QWidget()
        self.tabDiffPattern.setObjectName("tabDiffPattern")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabDiffPattern)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabDiffPattern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.spinBox_BGParam0 = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_BGParam0.sizePolicy().hasHeightForWidth())
        self.spinBox_BGParam0.setSizePolicy(sizePolicy)
        self.spinBox_BGParam0.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_BGParam0.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_BGParam0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_BGParam0.setProperty("value", 20)
        self.spinBox_BGParam0.setObjectName("spinBox_BGParam0")
        self.gridLayout_5.addWidget(self.spinBox_BGParam0, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinBox_BGParam1 = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_BGParam1.sizePolicy().hasHeightForWidth())
        self.spinBox_BGParam1.setSizePolicy(sizePolicy)
        self.spinBox_BGParam1.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_BGParam1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_BGParam1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_BGParam1.setProperty("value", 10)
        self.spinBox_BGParam1.setObjectName("spinBox_BGParam1")
        self.gridLayout_5.addWidget(self.spinBox_BGParam1, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.spinBox_BGParam2 = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_BGParam2.sizePolicy().hasHeightForWidth())
        self.spinBox_BGParam2.setSizePolicy(sizePolicy)
        self.spinBox_BGParam2.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_BGParam2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_BGParam2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_BGParam2.setProperty("value", 20)
        self.spinBox_BGParam2.setObjectName("spinBox_BGParam2")
        self.gridLayout_5.addWidget(self.spinBox_BGParam2, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 2, 1, 1)
        self.doubleSpinBox_Background_ROI_min = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_Background_ROI_min.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_Background_ROI_min.setSizePolicy(sizePolicy)
        self.doubleSpinBox_Background_ROI_min.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBox_Background_ROI_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Background_ROI_min.setDecimals(1)
        self.doubleSpinBox_Background_ROI_min.setMaximum(10000.0)
        self.doubleSpinBox_Background_ROI_min.setSingleStep(0.1)
        self.doubleSpinBox_Background_ROI_min.setProperty("value", 6.0)
        self.doubleSpinBox_Background_ROI_min.setObjectName("doubleSpinBox_Background_ROI_min")
        self.gridLayout_5.addWidget(self.doubleSpinBox_Background_ROI_min, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 2, 1, 1)
        self.doubleSpinBox_Background_ROI_max = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_Background_ROI_max.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_Background_ROI_max.setSizePolicy(sizePolicy)
        self.doubleSpinBox_Background_ROI_max.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBox_Background_ROI_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Background_ROI_max.setDecimals(1)
        self.doubleSpinBox_Background_ROI_max.setMaximum(10000.0)
        self.doubleSpinBox_Background_ROI_max.setSingleStep(0.1)
        self.doubleSpinBox_Background_ROI_max.setProperty("value", 21.0)
        self.doubleSpinBox_Background_ROI_max.setObjectName("doubleSpinBox_Background_ROI_max")
        self.gridLayout_5.addWidget(self.doubleSpinBox_Background_ROI_max, 1, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 2, 2, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tabDiffPattern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_8.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_13)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 1, 0, 1, 1)
        self.doubleSpinBox_ShiftY = QtWidgets.QDoubleSpinBox(self.groupBox_13)
        self.doubleSpinBox_ShiftY.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBox_ShiftY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_ShiftY.setMinimum(-99.99)
        self.doubleSpinBox_ShiftY.setMaximum(99.99)
        self.doubleSpinBox_ShiftY.setObjectName("doubleSpinBox_ShiftY")
        self.gridLayout_8.addWidget(self.doubleSpinBox_ShiftY, 1, 1, 1, 1)
        self.doubleSpinBox_ShiftX = QtWidgets.QDoubleSpinBox(self.groupBox_13)
        self.doubleSpinBox_ShiftX.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBox_ShiftX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_ShiftX.setMinimum(-99.99)
        self.doubleSpinBox_ShiftX.setObjectName("doubleSpinBox_ShiftX")
        self.gridLayout_8.addWidget(self.doubleSpinBox_ShiftX, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_13)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_13, 0, 4, 2, 1)
        self.pushButton_UpdatePlots_tab2 = QtWidgets.QPushButton(self.tabDiffPattern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_UpdatePlots_tab2.sizePolicy().hasHeightForWidth())
        self.pushButton_UpdatePlots_tab2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_UpdatePlots_tab2.setFont(font)
        self.pushButton_UpdatePlots_tab2.setObjectName("pushButton_UpdatePlots_tab2")
        self.gridLayout_4.addWidget(self.pushButton_UpdatePlots_tab2, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabDiffPattern, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1449, 22))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.mplactionOpen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.mplactionOpen.setFont(font)
        self.mplactionOpen.setObjectName("mplactionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionClose.setFont(font)
        self.actionClose.setObjectName("actionClose")
        self.mplactionSave_background = QtWidgets.QAction(MainWindow)
        self.mplactionSave_background.setObjectName("mplactionSave_background")
        self.mplactionSave_background_subtracted = QtWidgets.QAction(MainWindow)
        self.mplactionSave_background_subtracted.setObjectName("mplactionSave_background_subtracted")
        self.actionSet_range = QtWidgets.QAction(MainWindow)
        self.actionSet_range.setObjectName("actionSet_range")
        self.actionY_Scale = QtWidgets.QAction(MainWindow)
        self.actionY_Scale.setObjectName("actionY_Scale")
        self.mplactionPrint = QtWidgets.QAction(MainWindow)
        self.mplactionPrint.setObjectName("mplactionPrint")
        self.actionBackground_parameters = QtWidgets.QAction(MainWindow)
        self.actionBackground_parameters.setObjectName("actionBackground_parameters")
        self.mplactionNew_JList = QtWidgets.QAction(MainWindow)
        self.mplactionNew_JList.setObjectName("mplactionNew_JList")
        self.mplactionLoad_Jlist = QtWidgets.QAction(MainWindow)
        self.mplactionLoad_Jlist.setObjectName("mplactionLoad_Jlist")
        self.mplactionSave_JList = QtWidgets.QAction(MainWindow)
        self.mplactionSave_JList.setObjectName("mplactionSave_JList")
        self.mplactionEdit_JList = QtWidgets.QAction(MainWindow)
        self.mplactionEdit_JList.setObjectName("mplactionEdit_JList")
        self.mplactionShow_a_JCPDS_card = QtWidgets.QAction(MainWindow)
        self.mplactionShow_a_JCPDS_card.setObjectName("mplactionShow_a_JCPDS_card")
        self.mplactionXray_wavelength = QtWidgets.QAction(MainWindow)
        self.mplactionXray_wavelength.setObjectName("mplactionXray_wavelength")
        self.mplactionShow_Unshow_JList = QtWidgets.QAction(MainWindow)
        self.mplactionShow_Unshow_JList.setObjectName("mplactionShow_Unshow_JList")
        self.mplactionShow_a_JCPDS_file = QtWidgets.QAction(MainWindow)
        self.mplactionShow_a_JCPDS_file.setObjectName("mplactionShow_a_JCPDS_file")
        self.actionCiting_PeakPo = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionCiting_PeakPo.setFont(font)
        self.actionCiting_PeakPo.setObjectName("actionCiting_PeakPo")
        self.actionShortcut_keys = QtWidgets.QAction(MainWindow)
        self.actionShortcut_keys.setObjectName("actionShortcut_keys")
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionCiting_PeakPo)
        self.menuHelp.addAction(self.actionShortcut_keys)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label_4.setBuddy(self.spinBox_BGParam0)
        self.label_6.setBuddy(self.spinBox_BGParam2)
        self.label_5.setBuddy(self.spinBox_BGParam1)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PeakPo"))
        self.label_SessionFileName.setText(_translate("MainWindow", "Session filename"))
        self.label_DiffractionPatternFileName.setText(_translate("MainWindow", "Diffraction pattern filename"))
        self.label_DiffractionImageFilename.setText(_translate("MainWindow", "Diffraction image filename"))
        self.label_PONI.setText(_translate("MainWindow", "PONI filename"))
        self.label_Jlist.setText(_translate("MainWindow", "Jlist location"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Files), _translate("MainWindow", "Files"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sessions"))
        self.pushButton_LoadSession.setText(_translate("MainWindow", "Load"))
        self.pushButton_SaveSession.setText(_translate("MainWindow", "Save"))
        self.pushButton_ZipSession.setText(_translate("MainWindow", "Package"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Base pattern"))
        self.pushButton_NewBasePtn.setText(_translate("MainWindow", "New"))
        self.groupBox_24.setTitle(_translate("MainWindow", "File Navigation"))
        self.pushButton_FirstBasePtn.setText(_translate("MainWindow", "First"))
        self.pushButton_PrevBasePtn.setText(_translate("MainWindow", "<"))
        self.pushButton_NextBasePtn.setText(_translate("MainWindow", ">"))
        self.pushButton_LastBasePtn.setText(_translate("MainWindow", "Last"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Navigation setup"))
        self.radioButton_FileStep1.setText(_translate("MainWindow", "1"))
        self.radioButton_FileStep10.setText(_translate("MainWindow", "10"))
        self.radioButton_SortbyNme.setText(_translate("MainWindow", "Name"))
        self.radioButton_SortbyTime.setText(_translate("MainWindow", "Time"))
        self.groupBox.setTitle(_translate("MainWindow", "Pressure (GPa)"))
        self.radioButton_P10.setText(_translate("MainWindow", "10"))
        self.radioButton_P100.setText(_translate("MainWindow", "100"))
        self.radioButton_P01.setText(_translate("MainWindow", "0.1"))
        self.radioButton_P1.setText(_translate("MainWindow", "1"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Temperature (K)"))
        self.radioButton_T100.setText(_translate("MainWindow", "100"))
        self.radioButton_T10.setText(_translate("MainWindow", "10"))
        self.radioButton_T1.setText(_translate("MainWindow", "1"))
        self.radioButton_T1000.setText(_translate("MainWindow", "1000"))
        self.groupBox_11.setTitle(_translate("MainWindow", "T Shortcuts"))
        self.pushButton_2000K.setText(_translate("MainWindow", "2000 K"))
        self.pushButton_3000K.setText(_translate("MainWindow", "3000 K"))
        self.pushButton_1000K.setText(_translate("MainWindow", "1000 K"))
        self.pushButton_1500K.setText(_translate("MainWindow", "1500 K"))
        self.pushButton_RoomT.setText(_translate("MainWindow", "Room T"))
        self.pushButton_2500K.setText(_translate("MainWindow", "2500 K"))
        self.pushButton_3500K.setText(_translate("MainWindow", "3500 K"))
        self.pushButton_4000K.setText(_translate("MainWindow", "4000 K"))
        self.pushButton_4500K.setText(_translate("MainWindow", "4500 K"))
        self.pushButton_5000K.setText(_translate("MainWindow", "5000 K"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Main), _translate("MainWindow", "Main"))
        self.groupBox_6.setTitle(_translate("MainWindow", "View"))
        self.checkBox_SetToBasePtnLambda.setText(_translate("MainWindow", "Convert to base ptn wavelength"))
        self.checkBox_BasePtnBackground.setText(_translate("MainWindow", "Use base ptn background"))
        self.checkBox_IntNorm.setText(_translate("MainWindow", "Intensity nomalization"))
        self.pushButton_ApplyWaterfallChange.setText(_translate("MainWindow", "Apply"))
        self.groupBox_28.setTitle(_translate("MainWindow", "Gap"))
        self.groupBox_26.setTitle(_translate("MainWindow", "List"))
        self.pushButton_AddPatterns.setText(_translate("MainWindow", "Add"))
        self.pushButton_RemovePatterns.setText(_translate("MainWindow", "Remove"))
        self.pushButton_CleanPatterns.setText(_translate("MainWindow", "Clean"))
        self.groupBox_27.setTitle(_translate("MainWindow", "Selected"))
        self.pushButton_UpPattern.setText(_translate("MainWindow", "Up"))
        self.pushButton_DownPattern.setText(_translate("MainWindow", "Down"))
        self.pushButton_MakeBasePtn.setText(_translate("MainWindow", "Make Base Ptn"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Waterfall), _translate("MainWindow", "Waterfall"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Setup"))
        self.pushButton_AddRemoveCake.setText(_translate("MainWindow", "Add Cake"))
        self.pushButton_GetPONI.setText(_translate("MainWindow", "Get PONI"))
        self.groupBox_20.setTitle(_translate("MainWindow", "View"))
        self.label_9.setText(_translate("MainWindow", "Black"))
        self.label_8.setText(_translate("MainWindow", "White"))
        self.label_12.setText(_translate("MainWindow", "V Size"))
        self.pushButton_ApplyCakeView.setText(_translate("MainWindow", "Apply"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Mask out"))
        self.label_10.setText(_translate("MainWindow", "Min"))
        self.label_11.setText(_translate("MainWindow", "Max"))
        self.pushButton_ApplyMask.setText(_translate("MainWindow", "Apply"))
        self.groupBox_19.setTitle(_translate("MainWindow", "1D pattern"))
        self.pushButton_BackToOriginal.setText(_translate("MainWindow", "Back to original"))
        self.pushButton_Reintegrate1D.setText(_translate("MainWindow", "Reintegrate 1D"))
        self.pushButton_OuputCHI.setText(_translate("MainWindow", "Output CHI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCake), _translate("MainWindow", "Cake"))
        self.groupBox_9.setTitle(_translate("MainWindow", "List"))
        self.pushButton_NewJlist.setText(_translate("MainWindow", "New"))
        self.pushButton_LoadJlist.setText(_translate("MainWindow", "Import"))
        self.pushButton_SaveJlist.setText(_translate("MainWindow", "Save"))
        self.pushButton_ExportXLS.setText(_translate("MainWindow", "Export"))
        self.groupBox_7.setTitle(_translate("MainWindow", "All items"))
        self.pushButton_CheckAllJCPDS.setText(_translate("MainWindow", "Check"))
        self.pushButton_UncheckAllJCPDS.setText(_translate("MainWindow", "Uncheck"))
        self.checkBox_Intensity.setText(_translate("MainWindow", "Intensity"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Selected"))
        self.pushButton_AddToJlist.setText(_translate("MainWindow", "Add"))
        self.pushButton_RemoveJCPDS.setText(_translate("MainWindow", "Remove"))
        self.pushButton_MoveUp.setText(_translate("MainWindow", "Up"))
        self.pushButton_MoveDown.setText(_translate("MainWindow", "Down"))
        self.pushButton_ExportToUCFit.setText(_translate("MainWindow", "UCFit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabJCPDSList), _translate("MainWindow", "JCPDS"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Selected"))
        self.pushButton_RemoveUClist.setText(_translate("MainWindow", "Remove"))
        self.pushButton_ExportXLS_2.setText(_translate("MainWindow", "Save to XLS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUnitCellFit), _translate("MainWindow", "UnitCellFit"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Actions"))
        self.pushButton_ViewJCPDS.setText(_translate("MainWindow", "View JCPDS"))
        self.pushButton_SaveCHI.setText(_translate("MainWindow", "Save BgSub.CHI"))
        self.pushButton_SaveXY.setText(_translate("MainWindow", "Save .XY"))
        self.pushButton_SaveJCPDS.setText(_translate("MainWindow", "Save JCPDS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOutput), _translate("MainWindow", "Output"))
        self.groupBox_5.setTitle(_translate("MainWindow", "BG parameters"))
        self.label_4.setText(_translate("MainWindow", "N Points (20):"))
        self.label_6.setText(_translate("MainWindow", "N Order (10):"))
        self.label_5.setText(_translate("MainWindow", "N Iteration (20):"))
        self.label_2.setText(_translate("MainWindow", "ROI Min:"))
        self.label.setText(_translate("MainWindow", "ROI Max:"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Others"))
        self.label_7.setText(_translate("MainWindow", "Shift Y (%)"))
        self.label_3.setText(_translate("MainWindow", "Shift X"))
        self.pushButton_UpdatePlots_tab2.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiffPattern), _translate("MainWindow", "Processing"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.mplactionOpen.setText(_translate("MainWindow", "Open CHI file"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.mplactionSave_background.setText(_translate("MainWindow", "Save background"))
        self.mplactionSave_background_subtracted.setText(_translate("MainWindow", "Save background subtracted"))
        self.actionSet_range.setText(_translate("MainWindow", "Set range"))
        self.actionY_Scale.setText(_translate("MainWindow", "Y Scale (Lin/Log)"))
        self.mplactionPrint.setText(_translate("MainWindow", "Print"))
        self.actionBackground_parameters.setText(_translate("MainWindow", "Background parameters"))
        self.mplactionNew_JList.setText(_translate("MainWindow", "New JList"))
        self.mplactionLoad_Jlist.setText(_translate("MainWindow", "Load JList"))
        self.mplactionSave_JList.setText(_translate("MainWindow", "Save JList"))
        self.mplactionEdit_JList.setText(_translate("MainWindow", "Edit JList"))
        self.mplactionShow_a_JCPDS_card.setText(_translate("MainWindow", "Show a JCPDS card"))
        self.mplactionXray_wavelength.setText(_translate("MainWindow", "X-ray wavelength"))
        self.mplactionShow_Unshow_JList.setText(_translate("MainWindow", "Show/Unshow JList"))
        self.mplactionShow_a_JCPDS_file.setText(_translate("MainWindow", "Show a JCPDS file"))
        self.actionCiting_PeakPo.setText(_translate("MainWindow", "Citing PeakPo"))
        self.actionShortcut_keys.setText(_translate("MainWindow", "Shortcut keys"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

